### ISSUE TITLE
Doubt regarding the POST request

### ISSUE THREAD

**Issue by VenkataBhaskarr** [Pradumnasaraf/OpenSource-API#18]
### What would you like to share?

I had a doubt regarding the POST request. I tried sending POST requests to the endpoint in postman but its giving 400 error

<img width="1061" alt="Screenshot 2022-12-21 at 7 44 58 PM" src="https://user-images.githubusercontent.com/111889155/208926010-59cbf493-7b0d-42cc-8be7-5c4a67994780.png">

**Comment by Pradumnasaraf** [comment]
Hey,

It is working fine. The message should be the body (`JSON`) not in para. I have mentioned in the README

**Comment by VenkataBhaskarr** [comment]
My bad. It's working fine (confused between the body and params)
