### ISSUE TITLE
[BUG] fix `prettier.yml` workflow version number

### ISSUE THREAD

**Issue by Pradumnasaraf** [Pradumnasaraf/OpenSource-API#36]
### Description

Fix the version of 2 actions

```diff
- uses: actions/checkout@v2
+ uses: actions/checkout@v3
```

```diff
- uses: actions/setup-node@v2
+ uses: actions/setup-node@v3
```

File path - https://github.com/Pradumnasaraf/OpenSource-API/blob/main/.github/workflows/prettier.yml

**Comment by tarunsamanta2k20** [comment]
I would like to work on this issue

**Comment by 20A31A0558** [comment]
Hey @Pradumnasaraf 
if no one is assigned to this issue, I would like to work on this.

**Comment by AyonChowdhury1307** [comment]
I want to work on this

**Comment by Pradumnasaraf** [comment]
> I would like to work on this issue

Go ahead @tarunsamanta2k20 others please look at different issues. As they have commented 1st

**Comment by Pradumnasaraf** [comment]
> Hey @Pradumnasaraf if no one is assigned to this issue, I would like to work on this.

Go ahead @20A31A0558
