### ISSUE TITLE
[BUG] fix `publish-ghcr.yml` workflow version number

### ISSUE THREAD

**Issue by Pradumnasaraf** [Pradumnasaraf/OpenSource-API#37]
### Description

Update the 3 actions to the latest version

```diff
- uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
+ docker/login-action@v2
```

```diff
- uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
+ docker/metadata-action@v4
```

```diff
- uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
+ docker/build-push-action@v4
```

File path -https://github.com/Pradumnasaraf/OpenSource-API/blob/main/.github/workflows/publish-ghcr.yml

**Comment by tarunsamanta2k20** [comment]
I would like to work on this issue

**Comment by Pradumnasaraf** [comment]
> I would like to work on this issue

Go ahead. Please don't comment below every issue. Let other people also work on some. Thank you.

**Comment by SJ-Kumar** [comment]
Please assign this issue for me.

**Comment by AyonChowdhury1307** [comment]
I want to work on this

**Comment by dixitrathi7** [comment]
pls assign me @Pradumnasaraf , thanks

**Comment by NikhilRaikwar** [comment]
Hello @Pradumnasaraf  Bro, I'm interested in working on this issue. Would you be willing to assign it to me? I'm excited to help out and I'll do my best to resolve this issue as quickly as possible. Please let me know if there's anything I can do to help. Thanks!

**Comment by Pradumnasaraf** [comment]
Hey, @tarunsamanta2k20 are you working on this?

**Comment by AyonChowdhury1307** [comment]
Hey @Pradumnasaraf i want to work on this issue.

**Comment by Pradumnasaraf** [comment]
Looks like the previous person will not work on this issue.

Hey, @SJ-Kumar would you like to work on this (because you comment after that) otherwise @AyonChowdhury1307 will ready to fix this issue.

**Comment by VarchasvH** [comment]
Hey @Pradumnasaraf I would also like to work on this issue.

**Comment by AyonChowdhury1307** [comment]
hey @Pradumnasaraf i am fixing this issue.

**Comment by Pradumnasaraf** [comment]
Hey, @VarchasvH,

Please look for different issues someone is already working on this.

**Comment by VarchasvH** [comment]
> Hey, @VarchasvH,
> 
> Please look for different issues someone is already working on this.

Okk
